version: '2.1'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      NOD_ENV: development
      PORT: 4001
      ENV_PATH: .env.development 
      TERM: xterm
    ports:
      - '4001:4001'
    depends_on:
      - database
    volumes:
      - .:/home/app/capstone_api
  database:
    image: mongo:4.0.6
    volumes:
      - ../data:/data/db
    ports:
      - "27029:27017"