version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /feature-.*/
        - /circle-ci/
    docker:
      - image: circleci/node:10.15.1
      - image: circleci/mongo:4.0.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
