version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
    - image: circleci/node:10.15.1
    - image: mongo:4.0.6
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install-npm-wee
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test
    - run:
        name: code-coverage
        command: ./node_modules/.bin/nyc report --reporter=text-lcov
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
    - store_test_results:
        path: test-results.xml
workflows:
  version: 2
  workflow:
    jobs:
    - build
